name: cloud-kadai

services:
  web:
    build: .
    ports:
      - 80:5173

  mysql:
    image: mysql:9.4.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=family_restaurant
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - ./dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql:ro,Z
      - ./dbdata:/var/lib/mysql:Z
